VIA_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_MAP_ENABLE = yes
OS_DETECTION_ENABLE = yes
# Size trimming for ATmega32U4 (keep OS detection enabled)
#TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
REPEAT_KEY_ENABLE = no
#MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
#EXTRAKEY_ENABLE = no
BOOTMAGIC_ENABLE = no
NKRO_ENABLE = no
AUDIO_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
CAPS_WORD_ENABLE = no
AUTO_SHIFT_ENABLE = no
LAYER_LOCK_ENABLE = no

OPT_DEFS += -DENCODER_MAP_ENABLE
ifeq ($(strip $(ENCODER_HOT_SWAP_ENABLE)), yes)
	OPT_DEFS += -DENCODER_HOT_SWAP_ENABLE
	OPT_DEFS += -DMATRIX_REMAP_ENABLE
	SRC += ../common/matrix_remap.c
endif

$(eval $(call ATTACK25_CUSTOMISE_MSG))
$(info )
