#ifdef ENCODER_HOT_SWAP_ENABLE
#    define ENCODER_RESOLUTION 2
#    define ENCODER_DIRECTION_FLIP

#    define SWAP_ENCODERS_SW {{0, 5}}
#    define SWAP_ENCODERS_SW_REMAP_DST {{4, 0}}
#    define MATRIX_REMAP_TABLE_SRC SWAP_ENCODERS_SW
#    define MATRIX_REMAP_TABLE_DST SWAP_ENCODERS_SW_REMAP_DST
#endif

//#define NO_USB_STARTUP_CHECK
#define USB_SUSPEND_WAKEUP_DELAY 500

#define NUMLOCK_INDICATOR_COLOR HSV_GREEN

//#define VIA_EEPROM_CUSTOM_CONFIG_SIZE 1 // Custom config starts after VIA's EEPROM usage
